"""Live search prompts and key events from VastDB (generated by prompt-suggester)."""
import logging

from fastapi import APIRouter, HTTPException, status

from src.services.auth_service import CurrentUser
from src.services.suggestions_service import get_suggestions_service

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/suggestions", tags=["Suggestions"])


@router.get("")
async def get_suggestions(current_user: CurrentUser):
    """Latest batch of search prompts + key events for UI."""
    try:
        return get_suggestions_service().get_suggestions(current_user)
    except Exception as exc:
        logger.error("[SUGGESTIONS] %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to load suggestions: {exc}",
        ) from exc
